const express = require("express");
const cors = require("cors");
const mongoose = require("mongoose");
const axios = require("axios");
const puppeteer = require("puppeteer");
const jwt = require("jsonwebtoken");
const bcrypt = require("bcryptjs");
require("dotenv").config();

const app = express();
app.use(cors());
app.use(express.json());

// MongoDB connection
mongoose.connect(process.env.MONGO_URI);

// ---------- Models ----------

const UserSchema = new mongoose.Schema({
  name: String,
  email: { type: String, unique: true },
  password: String,
  createdAt: { type: Date, default: Date.now },
});
const User = mongoose.model("User", UserSchema);

const ReportSchema = new mongoose.Schema({
  query: String,
  report: String,
  sections: Object,
  userId: String,
  createdAt: { type: Date, default: Date.now },
});
const Report = mongoose.model("Report", ReportSchema);

// ---------- Middleware ----------

const authMiddleware = (req, res, next) => {
  const token = req.headers.authorization?.split(" ")[1];
  if (!token) return res.status(401).json({ error: "No token" });
  try {
    req.user = jwt.verify(token, process.env.JWT_SECRET);
    next();
  } catch {
    res.status(401).json({ error: "Invalid token" });
  }
};

// ---------- Auth routes ----------

app.post("/api/signup", async (req, res) => {
  const { name, email, password } = req.body;
  try {
    const hashed = await bcrypt.hash(password, 10);
    const user = await User.create({ name, email, password: hashed });
    const token = jwt.sign(
      { id: user._id, name: user.name },
      process.env.JWT_SECRET,
    );
    res.json({ token, name: user.name });
  } catch {
    res.status(400).json({ error: "Email already exists" });
  }
});

app.post("/api/login", async (req, res) => {
  const { email, password } = req.body;
  try {
    const user = await User.findOne({ email });
    if (!user) return res.status(400).json({ error: "User not found" });
    const valid = await bcrypt.compare(password, user.password);
    if (!valid) return res.status(400).json({ error: "Wrong password" });
    const token = jwt.sign(
      { id: user._id, name: user.name },
      process.env.JWT_SECRET,
    );
    res.json({ token, name: user.name });
  } catch {
    res.status(500).json({ error: "Login failed" });
  }
});

// ---------- Analysis routes ----------

app.post("/api/analyze", authMiddleware, async (req, res) => {
  const { query } = req.body;
  if (!query) return res.status(400).json({ error: "Query required" });
  try {
    const { data } = await axios.post(
      `${process.env.AGENT_SERVICE_URL}/report`,
      { query },
    );
    const saved = await Report.create({
      query,
      report: data.report,
      sections: data.sections,
      userId: req.user.id,
    });
    res.json({ id: saved._id, report: data.report, sections: data.sections });
  } catch (err) {
    res.status(500).json({ error: "Analysis failed" });
  }
});

app.get("/api/reports", authMiddleware, async (req, res) => {
  const reports = await Report.find({ userId: req.user.id })
    .sort({ createdAt: -1 })
    .limit(20);
  res.json(reports);
});

app.post("/api/pdf", async (req, res) => {
  const { report, query } = req.body;
  try {
    const browser = await puppeteer.launch({ args: ["--no-sandbox"] });
    const page = await browser.newPage();
    await page.setContent(`
      <html>
      <head>
        <style>
          body { font-family: Arial, sans-serif; padding: 40px; color: #1a1a2e; line-height: 1.8; }
          h1 { color: #6366f1; border-bottom: 2px solid #6366f1; padding-bottom: 10px; }
          h2 { color: #312e81; margin-top: 30px; }
          h3 { color: #4338ca; }
          .header { background: #1a1a2e; color: white; padding: 30px; margin: -40px -40px 40px; }
          .header h1 { color: white; border-bottom: 2px solid #6366f1; }
          .footer { margin-top: 60px; text-align: center; color: #999; font-size: 12px; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>◈ FinAgent Research Report</h1>
          <p>Query: ${query}</p>
          <p>Generated: ${new Date().toLocaleDateString()}</p>
        </div>
        ${report.replace(/\n/g, "<br>").replace(/#{1,6} (.+)/g, "<h2>$1</h2>")}
        <div class="footer">Generated by FinAgent AI Research Platform</div>
      </body>
      </html>
    `);
    const pdf = await page.pdf({
      format: "A4",
      margin: { top: "20px", bottom: "20px" },
    });
    await browser.close();
    res.set({
      "Content-Type": "application/pdf",
      "Content-Disposition": "attachment; filename=report.pdf",
    });
    res.send(pdf);
  } catch (err) {
    res.status(500).json({ error: "PDF generation failed" });
  }
});

// ---------- Start server ----------

app.listen(process.env.PORT || 5000, () => {
  console.log(`Backend running on port ${process.env.PORT || 5000}`);
});
